[workspace]
members = ["methods", "relay"]

[workspace.dependencies]
risc0-build = { version = "0.16", path = "../../../risc0/build" }
risc0-zkvm = { version = "0.16", path = "../../../risc0/zkvm", default-features = false }
bonsai-sdk = { version = "0.2", path = "../../../bonsai/sdk" }
bonsai-ethereum-relay = { version = "0.2", path = "../../../bonsai/ethereum-relay" }
methods = { path = "./methods", package = "governance-methods" }

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
