[package]
name = "risc0-zkvm-circuit-gen"
version = "0.1.0"
edition = "2021"
links = "risc0-zkvm-circuit-gen"

[dependencies]
clap = { version = "3.1", features = ["derive"] }
risc0-zkvm-circuit = { version = "0.1", path = ".."}
