[package]
name = "battleship-methods-inner"
version = "0.1.0"
edition = "2021"

[target.riscv32im-unknown-none-elf.dependencies]
battleship-core = { path = "../../core" }
risc0-zkvm-guest = { path = "../../../../../risc0/zkvm/sdk/rust/guest" }

[profile.release]
lto = true
opt-level = "z"

[package.metadata.release]
release = false

[build-dependencies]
risc0-build = { path = "../../../../../risc0/build" }

[workspace]
