[package]
name = "risc0-zkvm-platform"
version = "0.11.0-rc.4"
edition = "2021"
description = "RISC Zero zero-knowledge VM"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

# This crate is a potential dependency of the rust standard library.
# As such, it should not depend on anything the rust standard library
# doesn't.
#
# Also, it needs special trickery to work with the rust standard
# library build scripts; see rustc-std-workspace-core/README.md in the
# rust tree for details.
[dependencies]
compiler_builtins = { version = "0.1", optional = true }
core = { optional = true, package = "rustc-std-workspace-core", version = "1.0.0" }

[features]
rustc-dep-of-std = ["core", "compiler_builtins"]
