[package]
name = "risc0-zkp-verify"
version = "0.1.0"
edition = "2021"
description = "RISC Zero zero-knowledge proof system verify crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
risc0-zkp-core = { version = "0.1", path = "../core"}
