[package]
name = "risc0-sys"
description = "Generated / Native / HAL code for RISC Zero"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
links = "risc0-sys"

[build-dependencies]
cc = "1.0"
risc0-build-kernel = { workspace = true }

[dependencies]
cust = { version = "0.3", optional = true }
sppark = { git = "https://github.com/supranational/sppark.git", rev = "17119848e21491244125d266b2d74f26be2514f0", optional = true }

[features]
default = []
cuda = ["dep:cust", "dep:sppark"]
metal = []
