[package]
name = "risc0-circuit-fib"
version = "0.11.1"
edition = "2021"
description = "RISC Zero fibonacci circuit"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
anyhow = { version = "1.0", default-features = false }
risc0-zkp = { version = "0.11", path = "../..", default-features = false }

