[package]
name = "bonsai-ethereum-relay"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
ethers-solc = "1.0.2"

[dependencies]
anyhow = "1.0"
bincode = "1.3"
bonsai-sdk = { path = "../../../../bonsai/sdk" }
bonsai-starter-methods = { path = "../methods" }
bytemuck = "1.13.1"
clap = { version = "4.3", features = ["derive", "env"] }
ethers = { version = "=2.0.2", features = ["rustls", "ws"] }
ethers-signers = { version = "2.0.2", features = ["aws"] }
hex = "0.4.3"
risc0-build = { path = "../../../../risc0/build", features = ["guest-list"] }
risc0-zkvm = { path = "../../../../risc0/zkvm" }
tokio = { version = "1.19", features = ["full", "sync"] }

[features]
cuda = ["risc0-zkvm/cuda"]
metal = ["risc0-zkvm/metal"]
solidity_compile = []
