[workspace]
members = [
  "examples/rust/battleship",
  "examples/rust/battleship/core",
  "examples/rust/battleship/proof",
  "examples/rust/digital_signature",
  "examples/rust/digital_signature/core",
  "risc0/core",
  "risc0/zkvm/sdk/rust/core",
  "risc0/zkvm/sdk/rust/guest",
  "risc0/zkvm/sdk/rust/host",
  "risc0/zkvm/sdk/rust/serde",
]
