[workspace]
resolver = "2"
members = [
  "risc0/build",
  "risc0/circuit/rv32im",
  "risc0/r0vm",
  "risc0/tools",
  "risc0/zeroio",
  "risc0/zeroio_derive",
  "risc0/zkp",
  "risc0/zkvm",
  "risc0/zkvm/methods",
  "risc0/zkvm/platform",
]

[workspace.package]
version = "0.12.0"
edition = "2021"

[profile.bench]
lto = true

# Always optimize; otherwise tests take excessively long.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
