[workspace]
resolver = "2"
members = [
  "risc0/build",
  "risc0/circuit/rv32im",
  "risc0/r0vm",
  "risc0/tools",
  "risc0/zeroio",
  "risc0/zeroio_derive",
  "risc0/zkp",
  "risc0/zkvm",
  "risc0/zkvm/methods",
  "risc0/zkvm/platform",
]

[workspace.package]
version = "1.0.0-rc.2"
edition = "2021"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[profile.bench]
lto = true

# Always optimize; otherwise tests take excessively long.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
