[workspace]
members = [
  "examples/rust/battleship",
  "examples/rust/battleship/core",
  "risc0/core",
  "risc0/r0vm/rust/core",
  "risc0/r0vm/rust/guest",
  "risc0/r0vm/rust/host",
  "risc0/r0vm/rust/serde",
]
