[workspace]
members = [
  "examples/rust/battleship",
  "examples/rust/digital_signature",
  "examples/rust/votingmachine",
  "risc0/core",
  "risc0/zkvm/sdk/rust/core",
  "risc0/zkvm/sdk/rust/host",
  "risc0/zkvm/sdk/rust/serde",
]
