[package]
name = "risc0-benchmark-methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
blake3 = { version = "1.4", default-features = false }
ed25519-dalek = {version = "2.0.0-rc.3", default-features = false}
hex-literal = "0.4"
k256 = { version = "=0.13.1", features = ["arithmetic", "serde", "expose-field", "std", "ecdsa"], default_features = false }
risc0-zkvm = { path = "../../../risc0/zkvm", default-features = false, features = ["std"] }
risc0-zkp = { path = "../../../risc0/zkp", default-features = false }
sha3 = { version = "0.10", default-features = false }

[patch.crates-io]
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.2-risc0" }
ed25519-dalek = { git = "https://github.com/risc0/curve25519-dalek", branch = "capossele/fix-hex" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.1-risc0"  }
