[package]
name = "risc0-zkvm"
version = { workspace = true }
edition = { workspace = true }
description = "RISC Zero zero-knowledge VM"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[[bench]]
name = "fib"
harness = false

[[bench]]
name = "guest_run"
harness = false

[build-dependencies]
prost-build = { version = "0.11", optional = true }
protobuf-src = { version = "1.1", optional = true }

[dependencies]
anyhow = { version = "1.0", default-features = false }
bytemuck = "1.12"
cfg-if = "1.0"
risc0-circuit-rv32im = { version = "0.12", path = "../circuit/rv32im", default-features = false }
risc0-zeroio = { path = "../zeroio", default-features = false }
risc0-zkp = { version = "0.12", path = "../zkp", default-features = false }
risc0-zkvm-platform = { version = "0.12", path = "platform" }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
tracing = { version = "0.1", default-features = false, features = ["attributes"] }

# TODO(nils): Change these `target_os` checks to `target_vendor` checks when we
# have a real target triple.
#
# Host dependencies
[target.'cfg(not(target_os = "zkvm"))'.dependencies]
addr2line = { version = "0.19", optional = true }
elf = "0.7"
gimli = { version = "0.27", optional = true }
lazy-regex = "2.3"
log = "0.4"
num-traits = "0.2"
num-derive = "0.3"
prost = { version = "0.11", optional = true }
rand = "0.8"
rayon = "1.5"
sha2 = "0.10"
thiserror = "1.0"

[target.'cfg(target_os = "zkvm")'.dependencies]
# Lots of things depend on getrandom, and it throws a compiler error
# for environments it doesn't support.  So, we depend on it here to
# add the "custom" feature flag.
#
# To actually use getrandom, one must provide a custom implementation per
# https://docs.rs/getrandom/latest/getrandom/#custom-implementations or it
# will panic.
getrandom = { version = "0.2", features = ["custom"] }

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
clap = { version = "4.0", features = ["derive"] }
criterion = "0.4"
tempfile = "3.3"
tracing-forest = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(not(target_os = "zkvm"))'.dev-dependencies]
env_logger = "0.10"
lazy_static = "1.4"
risc0-zkvm-methods = { path = "methods" }
serial_test = "0.9"
tar = "0.4"
tempdir = "0.3"
test-log = { version = "0.2", features = ["trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
cuda = ["risc0-circuit-rv32im/cuda", "risc0-zkp/cuda"]
default = ["std"]
dual = []
insecure_skip_seal = []
metal = []
profiler = ["dep:addr2line", "dep:gimli", "dep:prost", "dep:prost-build", "dep:protobuf-src"]
std = ["anyhow/std", "risc0-circuit-rv32im/std", "risc0-zeroio/std", "risc0-zkp/std", "serde/std"]
verify-only = ["risc0-circuit-rv32im/verify-only"]
