[package]
name = "risc0-zkp-hal"
version = "0.9.0"
edition = "2021"
description = "RISC Zero zero-knowledge proof system hardware abstraction layer crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
downcast-rs = "1.2"
rand = "0.8"
rayon = "1.5"
risc0-zkp-core = { version = "0.9", path = "../core" }
