[package]
name = "risc0-r0vm"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.9" }
clap = { version = "3.2", features = ["derive"] }
risc0-zkvm = { version = "0.10", path = "../sdk/rust" }

[dev-dependencies]
anyhow = "1.0"
assert_cmd = "2.0"
risc0-zkvm-methods = { path = "../sdk/rust/methods" }
