[package]
name = "battleship-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
postcard = { version = "0.7", default-features = false, features = ["alloc"] }
risc0 = { path = "../../../../risc0/r0vm/rust/device" }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
