[package]
name = "risc0-zkvm-host"
version = "0.1.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM host crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
ctor = "0.1"
cxx = "1.0"
log = "0.4"
risc0-zkvm-host-sys = { version = "0.1", path = "../../cpp/host" }

[build-dependencies]
cxx-build = "1.0"
