[package]
name = "risc0-zkvm-circuit"
version = "0.11.1"
edition = "2021"
description = "RISC Zero zero-knowledge VM circuit"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
anyhow = { version = "1.0", default-features = false }
log = "0.4"
risc0-zkp = { version = "0.11", path = "../../../../zkp/rust", default-features = false, features = ["verify"] }

[dev-dependencies]
env_logger = "0.9"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
glob = "0.3"

[features]
default = ["cpp"]
cpp = ["std"]
std = []
