[package]
name = "xtask"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
clap = { version = "4.0", features = ["derive"] }
semver = "1.0"
svm-rs = { version = "0.2", features = ["blocking"] }

[package.metadata.release]
release = false
