[package]
name = "xtask"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
clap = { version = "4.0", features = ["derive"] }
which = "4.4"
xshell = "0.2"

[package.metadata.release]
release = false
