name: sccache install
description: Install sccache
runs:
  using: composite
  steps:
    - if: runner.os == 'Linux' && runner.arch == 'X64'
      run:
        SCCACHE_VERSION=v0.3.3
        SCCACHE_ARCH=x86_64-unknown-linux-musl
      shell: bash
      # run: |
      #   echo "SCCACHE_ARCH=x86_64-unknown-linux-musl" >> $GITHUB_ENV
      #   SCCACHE_VERSION=v0.3.3

    - if: runner.os == 'macOS' && runner.arch == 'X64'
      run:
        SCCACHE_VERSION=v0.3.3
        SCCACHE_ARCH=x86_64-apple-darwin
      shell: bash
      # run: |
      #   echo "SCCACHE_ARCH=x86_64-apple-darwin" >> $GITHUB_ENV
      #   SCCACHE_VERSION=v0.3.3

    - if: runner.os == 'macOS' && runner.arch == 'ARM64'
      run:
        SCCACHE_VERSION=v0.3.3
        SCCACHE_ARCH=aarch64-apple-darwin
      shell: bash
      # run: |
      #   echo "SCCACHE_ARCH=aarch64-apple-darwin" >> $GITHUB_ENV
      #   SCCACHE_VERSION=v0.3.3

    - if: runner.os == 'Linux' &&  runner.arch == 'ARM64'
      run:
        SCCACHE_VERSION=v0.4.0-pre.5
        SCCACHE_ARCH=aarch64-unknown-linux-musl
      shell: bash
      # run: |
      #   echo "SCCACHE_ARCH=aarch64-unknown-linux-musl" >> $GITHUB_ENV
      #   SCCACHE_VERSION=v0.4.0-pre.5

    - env:
        SCCACHE_URL: https://github.com/mozilla/sccache/releases/download
        # SCCACHE_VERSION: $VERSION
      run: |
        SCCACHE_FILE=sccache-$SCCACHE_VERSION-$SCCACHE_ARCH
        curl -L "$SCCACHE_URL/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
        mkdir -p $HOME/.local/bin
        mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - if: runner.os != 'macOS'
      name: Cache rust target + HAL_CACHE
      uses: risc0/rust-cache@v2
      id: rust-cache
      with:
        key: rust-cache-${{ runner.os }}-${{ runner.arch }}
        # TODO: this path will not work on windows.
        cache-directories: ~/.cache/risc0

    - run: rm -f $HOME/.cargo/config
      shell: bash


# v0.3.3
        # curl -L "https://github.com/mozilla/sccache/releases/download/v0.4.0-pre.5/sccache-v0.4.0-pre.5-aarch64-unknown-linux-musl.tar.gz" | tar xz
        # mkdir -p $HOME/.local/bin
        # mv -f sccache-v0.4.0-pre.5-aarch64-unknown-linux-musl/sccache $HOME/.local/bin/sccache
        # echo "$HOME/.local/bin" >> $GITHUB_PATH
