[package]
name = "risc0-zkp-core"
version = "0.1.0"
edition = "2021"
description = "RISC Zero zero-knowledge proof system core crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
rand_core = "0.6"
sha2 = { version = "0.10", features = ["compress"] }
