[package]
name = "risc0-zkp-core"
version = "0.2.0"
edition = "2021"
description = "RISC Zero zero-knowledge proof system core crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"
links = "risc0-zkp-core"

# The cxx feature enables the C++ implementation of this crate.
# The pure feature enables the 'pure' rust implementation of this crate.
# Only one of `cxx` or `pure` must be selected.
[features]
default = ["pure"]
cxx = ["dep:cxx", "dep:risc0-core"]
pure = ["dep:rand", "dep:rand_core", "dep:sha2"]

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.9.1", features = ["derive"] }
cfg-if = "1.0"
cxx = { version = "1.0", optional = true }
rand = { version = "0.8", default-features = false, features = ["small_rng"], optional = true }
rand_core = {version = "0.6", optional = true }
risc0-core = { version = "0.1", path = "../../core", optional = true }
sha2 = { version = "0.10", features = ["compress"], optional = true }

[build-dependencies]
cxx-build = "1.0"
