[package]
name = "risc0-zkp-core"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayref = "0.3"
generic-array = "0.14"
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
rand_core = "0.6"
sha2 = { version = "0.10", features = ["compress"] }
typenum = "1.15"
