[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
revm = { version= "2.3.1", default-features = false, features = ["std", "k256", "with-serde"] }
getrandom = { version = "0.2", features = ["custom"] }
primitive-types = "0.12.1"
bytes = { version = "1.1", default-features = false }
serde = "1.0"
hashbrown = "0.13"

# For 'ethers'
ethers-providers = { version = "1.0.2", optional = true}
ethers-core = { version = "1.0.2", optional = true}
tokio = { version = "1.23", features = [
    "rt-multi-thread",
    "macros",
], optional = true }
futures = { version = "0.3.24", optional = true }

[features]
default = ["ethers"]
ethers = ["tokio", "ethers-providers", "ethers-core", "futures"]