[package]
name = "battleship"
version = "0.1.0"
edition = "2021"

[dependencies]
battleship-core = { path = "core" }
log = "0.4"
zkvm-core = { path = "../../../risc0/zkvm/sdk/rust/core" }
zkvm-host = { path = "../../../risc0/zkvm/sdk/rust/host" }
zkvm-serde = { path = "../../../risc0/zkvm/sdk/rust/serde" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
