[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
hello-world-methods = { path = "methods" }
risc0-zkvm = { path = "../../risc0/zkvm", features = ["profiler"] }
serde = "1.0"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
metal = ["risc0-zkvm/metal"]
prove = ["risc0-zkvm/prove"]
