[package]
name = "risc0-zkvm-verify"
version = "0.10.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM verify crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
anyhow = "1.0"
array-init = "2.0"
bytemuck = { version = "1.9", features = ["derive"] }
paste = "1.0"
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
rand_core = "0.6"
risc0-zkp = { version = "0.10", path = "../../../../zkp/rust" }
risc0-zkvm = { version = "0.10", path = ".." }
serde = { version = "1.0", features = ["derive"] }
sha2 = { version = "0.10", features = ["compress"] }

[dev-dependencies]
bencher = "0.1.5"
env_logger = "0.9"
log = "0.4"
test-log = "0.2"

[[bench]]
name = "verify"
harness = false

[features]
default = ["prove", "verify"]
prove = ["risc0-zkp/hal"]
verify = []
