[package]
name = "risc0-tools"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "RISC Zero devtools"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
log = "0.4.7"
risc0-core = { workspace = true }
risc0-zkvm = { workspace = true, features = ["default"] }
regex = "1"
tempdir = "0.3"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.3"
