[package]
name = "risc0-tools"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "RISC Zero devtools"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
risc0-zkvm = { version = "0.12", path = "../zkvm", features = ["profiler"] }

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.3"
