[package]
name = "risc0-zkvm-core"
version = "0.2.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM core crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = []
