[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
{% if risc0_crate_branch %}
risc0-build = { git = "https://github.com/risc0/risc0.git", branch = "{{ risc0_crate_branch }}" }
{% else %}
risc0-build = "{{ risc0_version }}"
{% endif %}

[package.metadata.risc0]
methods = ["guest"]
