[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
{% if risc0_crate_branch %}
risc0-build = { git = "https://github.com/risc0/risc0.git", branch = "{{ risc0_crate_branch }}" }
{% else %}
risc0-build = "{{ risc0_version }}"
{% endif %}

[dependencies]
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
{% if risc0_crate_branch %}
risc0-zkvm = { git = "https://github.com/risc0/risc0.git", branch = "{{ risc0_crate_branch }}", default-features = false }
{% else %}
risc0-zkvm = { version = "{{ risc0_version }}", default-features = false }
{% endif %}
