[package]
name = "prorata-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
rust_decimal = { version = "1.29", features = ["serde-str"] }
rust_decimal_macros = "1.29"
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
sha2 = "0.10.6"
