[package]
name = "battleship-core"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm-core = { path = "../../../../risc0/zkvm/sdk/rust/core", default-features = false, features = ["pure"] }
serde = { version = "1.0", default-features = false }

[dev-dependencies]
battleship-methods = { path = "../methods" }
ctor = "0.1"
env_logger = "0.8"
log = "0.4"
risc0-zkvm-host = { path = "../../../../risc0/zkvm/sdk/rust/host" }
risc0-zkvm-serde = { path = "../../../../risc0/zkvm/sdk/rust/serde" }
tempfile = "3.3"

[package.metadata.release]
release = false
