[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { path = "../../../../risc0/build", features = ["guest-list"] }

[dependencies]
risc0-build = { path = "../../../../risc0/build", features = ["guest-list"] }

[dev-dependencies]
hex-literal = "0.4.1"
risc0-zkvm = { path = "../../../../risc0/zkvm" }
