[package]
name = "risc0-benchmark-lib"
version = "0.18.0"
edition = "2021"

[dependencies]
merkletree = { git = "https://github.com/capossele/merkletree", branch= "capossele/risc0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
sha2 = { version = "0.10.6", default_features = false }

[features]
cuda = []
metal = []
