[package]
name = "zkevm-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1.1", default-features = false }
ethers-core = { git = "https://github.com/gakonst/ethers-rs", rev = "8175f0f97070ad69abd5dfa7b8df31f1c1dcc3d6", optional = true }
ethers-providers = { git = "https://github.com/gakonst/ethers-rs", rev = "8175f0f97070ad69abd5dfa7b8df31f1c1dcc3d6", optional = true }
primitive-types = { version = "0.12", features = ["serde"] }
revm = { version = "3.5", default-features = false, features = [
  "std",
  "serde",
] }
serde = "1.0"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
], optional = true }

[features]
default = ["ethers"]
ethers = ["tokio", "ethers-providers", "ethers-core"]
