[package]
name = "risc0-zkvm-circuit"
version = "0.1.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM circuit crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"
links = "risc0-zkvm-circuit"

[dependencies]
anyhow = "1.0"
cxx = "1.0"
risc0-zkp-core = { version = "0.2", path = "../../zkp/core", features = ["cxx"] }
risc0-zkvm-platform = { version = "0.1", path = "../platform"}

[build-dependencies]
cxx-build = "1.0"
