[package]
name = "risc0-zkvm-circuit"
version = "0.1.0"
edition = "2021"
links = "risc0-zkvm-circuit"

[dependencies]
cxx = "1.0"
clap = { version = "3.1", features = ["derive"] }
risc0-zkp-core = { version = "0.2", path = "../../zkp/core" }
risc0-zkvm-platform = { version = "0.1", path = "../platform"}

[build-dependencies]
cxx-build = "1.0"
