[package]
name = "prorata-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
prorata-core = { path = "../core", features = ["host"] }
risc0-zkvm = { path = "../../../risc0/zkvm" }
serde = "1.0"
rust_decimal = "1.29"
rust_decimal_macros = "1.29"
bincode = "1.3.3"
clap = { version = "4.3", features = ["derive"] }
ciborium = "0.2.1"
