[package]
name = "risc0-zkvm-verify"
version = "0.2.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM verify crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"
links = "risc0-zkvm-verify"

# The cxx feature enables the C++ implementation of this crate.
# The pure feature enables the 'pure' rust implementation of this crate.
# Only one of `cxx` or `pure` must be selected.
[features]
default = ["pure", "std"]
cxx = [
  "dep:cxx",
  "dep:risc0-core",
  "dep:risc0-zkvm-circuit",
  "dep:risc0-zkvm-circuit-gen",
  "risc0-zkp-core/cxx",
]
pure = ["dep:risc0-zkp-verify", "dep:risc0-zkvm-serde", "dep:serde"]
serde = ["serde/std"]
std = ["serde"]

[dependencies]
cfg-if = "1.0"
cxx = { version = "1.0", optional = true }
risc0-core = { version = "0.1", path = "../../core", optional = true }
risc0-zkp-core = { version = "0.2", path = "../../zkp/core" }
risc0-zkp-verify = { version = "0.2", path = "../../zkp/verify", optional = true }
risc0-zkvm-circuit = { version = "0.1", path = "../circuit", optional = true }
risc0-zkvm-circuit-gen = { version = "0.1", path = "../circuit/make-circuit", optional = true }
risc0-zkvm-serde = { version = "0.2", path = "../../zkvm/sdk/rust/serde", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }

[build-dependencies]
cxx-build = "1.0"

[dev-dependencies]
bencher = "0.1.5"
env_logger = "0.9"
log = "0.4"
test-log = "0.2"

[[bench]]
name = "verify"
harness = false
