[package]
name = "train-model"
version = "0.1.0"
edition = "2021"

[workspace]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.33.2"
serde_json = "1.0.107"
smartcore = {version = "0.3.2", features = ["serde"]}
rmp-serde = "1.1.2"
