# Defines a profile configuration for a specific crate.
# Lines containing a single `#` are placeholders for the user to fill in.

### Specify the crate name.
## Mandatory
name = 'zip'

### Specify a list of versions to be built.
## Mandatory
versions = ['0.6.4']

### Instructs whether to use the standard library or not.
## Optional, default: false
std = true

### Instructs whether to use the fast mode or not, by enabling
### `RISC0_EXPERIMENTAL_PREFLIGHT` feature.
## Optional, default: true
# fast_mode = true/false

############## NOTE ##############
# Either `risc0_gh_branch` or    #
# `risc0_path` must be specified #
# but not both.                  #
##################################

### Define which Github branch should be used for templates and crate imports.
## Optional, default: None
# risc0_gh_branch = "<branch>"

### Define a local path to a RISC0 repository, which will be used for templates
### and crate imports.
## Optional, default: None
# risc0_path = "<path>"

### Injects a custom `main` function body into the crate.
## Optional, default: None
# custom_main = 'println!("Hello, world!");'

### Inject a top level scop string, e.g. `use lazy_static::lazy_static;`
## Optional, default: None
# import_str = '<import-string>'

### Informs whether we should run the prover to test the guest crate.
## Optional, default: false
# run_prover = true/false

### Informs whether we should expect the build/run steps to fail or not.
## Optional, default: false
# should_fail = true/false

### Toggles if we should inject CC flags
### Reference: https://github.com/risc0/risc0/issues/443
## Optional, default: false
inject_cc_flags = true

### Specify a list of crates to be patched.
## Optional, default: None
# patch = '''
# [patch.crates-io]
# <crate-dependency-1> = { git = "<git-url>", rev = "<git-rev>" }
# <crate-dependency-2> = { version = "<version>", features = ["<feature-1>", "<feature-2>"] }
# '''
