[package]
name = "doc-test"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[package.metadata.release]
release = false

[dependencies]
fibonacci-methods = { path = "../../examples/profiling/methods" }
risc0-zkvm = { workspace = true, features = ["prove", "profiler"] }
risc0-zkvm-methods = { path = "../../risc0/zkvm/methods" }

[build-dependencies]
glob = "0.3"
