[package]
name = "checkmate"
version = "0.12.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = { path = "../../../risc0/build" }

[dependencies]
shakmaty = "0.22"
risc0-zkvm = { path = "../../../risc0/zkvm", default-features = false, features = ["std"] }
chess-core = { path = "../../chess/core" }
