[package]
name = "multiply"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false }
# TODO(victor): Refactor such that this import is not required.
risc0-zkvm-platform = { path = "../../../../risc0/zkvm/platform", features = ["panic_impl"] }
