[package]
name = "chess-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { path = "../../../risc0/build" }
risc0-zkvm-platform = { path = "../../../risc0/zkvm/platform" }

[package.metadata.risc0]
methods = ["guest"]
