[package]
name = "ml_template"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false, features = [
  "std",
] }
smartcore = { version = "0.3", features = ["serde"]}

[patch.crates-io]
smartcore = { git = "https://github.com/risc0/smartcore.git", features = ['serde'] }
