[package]
name = "risc0-zkvm-host-sys"
version = "0.1.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM host (sys) crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"
links = "risc0-zkvm-host-sys"

[dependencies]
cxx = "1.0"
risc0-zkvm-prove = { version = "0.1", path = "../../../prove" }
risc0-zkvm-verify = { version = "0.2", path = "../../../verify" }

[build-dependencies]
cxx-build = "1.0"
