[package]
name = "r0vm-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
r0vm-core = { path = "../core" }
r0vm-serde = { path = "../serde" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
