[package]
name = "risc0-zkvm-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-zkvm = { version = "0.10", path = ".." }

[package.metadata.release]
release = false

[package.metadata.risc0]
methods = ["inner"]

