[package]
name = "risc0-zkvm"
version = "0.10.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
anyhow = "1.0"
bytemuck = "1.9"
cargo_metadata = "0.14"
cfg-if = "1.0"
risc0-zkp = { version = "0.10", path = "../../../zkp/rust", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
tempfile = "3.3"

# TODO(nils): Change these arch checks to vendor checks when we have a
# real target triple.
#
# Host dependencies
[target.'cfg(not(target_arch = "riscv32"))'.dependencies]
ctor = "0.1"
cxx = "1.0"
log = "0.4"
rand = "0.8"
reqwest = { version = "0.11", features = ["rustls-tls", "blocking"] }
risc0-zkvm-platform-sys = { version = "0.10", path = "../../platform" }
risc0-zkvm-sys = { version = "0.10", path = "../.." }
serde_json = "1.0"
sha2 = "0.10"
zip = "0.6"

[target.'cfg(not(target_arch = "riscv32"))'.dev-dependencies]
risc0-zkvm-methods = { version = "0.1", path = "methods" }

[target.'cfg(not(target_arch = "riscv32"))'.build-dependencies]
cxx-build = "1.0"

[features]
bazel = []
default = ["prove", "std", "verify"]
doc = ["std"]
prove = ["risc0-zkp/prove"]
# The pure feature enables the 'pure' rust implementation of this
# crate without any of the FFI interfaces exposed for e.g. the prover.
pure = []
std = ["risc0-zkp/std", "serde/std"]
verify = ["risc0-zkp/verify"]


[package.metadata.release]
release = false
