[package]
name = "risc0-zkvm"
version = "0.10.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
bytemuck = "1.9"
risc0-zkp = { version = "0.10", path = "../../../zkp/rust", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
tempfile = "3.3"

# TODO(nils): Change these arch checks to vendor checks when we have a
# real target triple.
#
# Host dependencies
[target.'cfg(not(target_arch = "riscv32"))'.dependencies]
anyhow = "1.0"
ctor = "0.1"
cxx = "1.0"
log = "0.4"
rand = "0.8"
risc0-zkvm-sys = { version = "0.10", path = "../.." }
sha2 = "0.10"
xmas-elf = "0.8"

[target.'cfg(not(target_arch = "riscv32"))'.dev-dependencies]
risc0-zkvm-methods = { version = "0.1", path = "methods" }

[features]
default = ["prove", "std", "verify"]
doc = ["std"]
prove = ["risc0-zkp/prove"]
std = ["risc0-zkp/std", "serde/std"]
verify = ["risc0-zkp/verify"]
