[package]
name = "digital-signature-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
r0vm-core = { path = "../../../../risc0/r0vm/rust/core" }
r0vm-device = { path = "../../../../risc0/r0vm/rust/device" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
