[package]
name = "risc0-r0vm"
version = { workspace = true }
edition = { workspace = true }
description = "RISC Zero zero-knowledge VM executable"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
anyhow = "1.0"
bytemuck = "1.12"
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.10.0"
risc0-zkvm = { version = "0.12", path = "../zkvm", features = ["profiler"] }

[dev-dependencies]
anyhow = "1.0"
assert_cmd = "2.0"
assert_fs = "1.0"
risc0-zkvm-methods = { path = "../zkvm/methods" }
