[package]
name = "battleship-methods"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = "z"

[package.metadata.release]
publish = false
release = false

[package.metadata.risc0]
methods = ["inner"]

[build-dependencies]
risc0-build = { path = "../../../../risc0/build" }
