[package]
name = "bonsai-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bincode = "1.3"
bytemuck = "1.13"
hex = "0.4"
reqwest = { version = "0.11", features = ["json", "blocking", "gzip"] }
risc0-zkvm = { workspace = true, features = ["prove"] }
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "3.0", features = ["base64", "time_0_3"] }
thiserror = { version = "1.0" }
time = "0.3"
tokio = { version = "1.19", features = ["full"] }
uuid = { version = "1.3", features = ["serde"] }
zstd = { version = "0.12" }

[dev-dependencies]
env_logger = "0.9.0"
httpmock = "0.6"
risc0-zkvm-methods = { workspace = true }
serde_json = "1.0"
uuid = { version = "1.3", features = ["v4"] }
wiremock = "0.5"
