[package]
name = "bonsai-sdk"
description = "Bonsai Software Development Kit"
version = "0.2.0"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
env_logger = "0.9.0"
httpmock = "0.6"
uuid = { version = "1.3", features = ["v4"] }

[lib]
# Disables the doctest from the README because it imports external components and make requests
doctest = false
