[package]
name = "digital-signature"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.1.6"
digital-signature-core = { path = "core" }
log = "0.4"
sha2 = "0.10.2"
zkvm-core = { path = "../../../risc0/zkvm/sdk/rust/core" }
zkvm-host = { path = "../../../risc0/zkvm/sdk/rust/host" }
zkvm-serde = { path = "../../../risc0/zkvm/sdk/rust/serde" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
