[package]
name = "risc0-zkvm-guest"
version = "0.1.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM guest crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
bytemuck = { version = "1.9" }
risc0-zkvm-core = { version = "0.2", path = "../core", default-features = false }
risc0-zkvm-serde = { version = "0.2", path = "../serde", default-features = false }
serde = { version = "1.0", default-features = false }
