[package]
name = "risc0-zkvm-guest"
version = "0.7.0-rc.1"
edition = "2021"
description = "RISC Zero zero-knowledge VM guest crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
bytemuck = { version = "1.9" }
risc0-zkp-core = { version = "0.7.0-dev.1", path = "../../../../zkp/rust/core" }
risc0-zkvm-core = { version = "0.7.0-dev.1", path = "../core", default-features = false, features = ["pure"] }
risc0-zkvm-serde = { version = "0.7.0-dev.1", path = "../serde", default-features = false }
serde = { version = "1.0", default-features = false }

[build-dependencies]
risc0-build = { version = "0.7.0-dev.1", path = "../../../../build" }

[features]
bazel = []

[package.metadata.docs.rs]
default-target = "riscv32im-unknown-none-elf"
cargo-args = ["-Z", "build-std=alloc,core"]
