[package]
name = "risc0-circuit-rv32im-sys"
description = "Generated code build for rv32im circuit"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]

[build-dependencies]
cc = "1.0"
glob = "0.3"
sha2 = "0.10"

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.24"

[features]
default = []
prove = []
cuda = []