[package]
name = "risc0-build-kernel"
description = "RISC Zero tool for building kernels"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
cc = { version = "1.0", features = ["parallel"] }
glob = "0.3"
hex = "0.4"
home = "0.5"
sha2 = "0.10"
tempfile = "3.3"

# cargo_metadata = "0.15"
# downloader = "0.2"
# home = "0.5"
# risc0-zkvm = { workspace = true, features = ["binfmt"] }
# risc0-zkvm-platform = { workspace = true }
# serde = { version = "1.0", default-features = false, features = ["derive"] }
# serde_json = "1.0"
# sha2 = "0.10"
# tempfile = "3.3"
# zip = "0.6"
