[workspace]

[package]
name = "risc0-zkvm-methods-inner"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "0.10", path = "../.." }
risc0-zkp = { version = "0.10", path = "../../../../../zkp/rust" }

[profile.release]
lto = true
opt-level = "z"

[build-dependencies]
risc0-zkvm = { version = "0.10", path = "../.." }

[package.metadata.release]
release = false

[features]
default = ["std"]
std = []
