[workspace]

[package]
name = "risc0-zkvm-methods-inner"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.11"
risc0-zkp = { version = "0.11", path = "../../../../../zkp/rust", default-features = false }
risc0-zkvm-guest = { version = "0.11", path = "../../guest", default-features = false, features = ["std"] }
risc0-zkvm-methods = { version = "0.1", path = "..", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[profile.release]
lto = true
opt-level = "z"

[build-dependencies]
risc0-build = { version = "0.11", path = "../../build" }

[package.metadata.release]
release = false

[features]
default = ["std"]
# Run rust-based prover instead of FFI-based prover.
pure-prove = ["risc0-zkvm-guest/pure-prove"]
std = []
test_feature1 = []
test_feature2 = []
