[workspace]

[package]
name = "risc0-zkvm-methods-inner"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkp = { version = "0.10", path = "../../../../../zkp/rust", default-features = false }
risc0-zkvm-guest = { version = "0.10", path = "../../guest", default-features = false, features = ["std"] }

[profile.release]
lto = true
opt-level = "z"

[build-dependencies]
risc0-build = { version = "0.10", path = "../../build" }

[package.metadata.release]
release = false

[features]
default = ["std"]
std = []
test_feature1 = []
test_feature2 = []
