[package]
name = "risc0-circuit-rv32im"
description = "RISC Zero circuit for rv32im"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[[bench]]
name = "eval_check"
harness = false

[[bin]]
name = "bench"
required-features = ["prove"]

[dependencies]
anyhow = { version = "1.0", default-features = false }
cfg-if = "1.0"
derive-debug = "0.1.2"
risc0-binfmt = { workspace = true }
risc0-core = { workspace = true }
risc0-zkp = { workspace = true }
risc0-zkvm-platform = { workspace = true }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
bytemuck = { version = "1.13", optional = true }
crossbeam = { version = "0.8", optional = true }
cust = { version = "0.3", optional = true }
lazy-regex = { version = "3.1", optional = true }
rand = { version = "0.8", optional = true }
rayon = { version = "1.5", optional = true }
metal = { version = "0.27", optional = true }
risc0-circuit-rv32im-sys = { workspace = true, optional = true }
sha2 = { version = "0.10", default-features = false, optional = true }
tracing-forest = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
], optional = true }

[dev-dependencies]
criterion = "0.5"
test-log = { version = "0.2", default-features = false, features = ["trace"] }

[features]
cuda = [
  "dep:cust",
  "prove",
  "risc0-circuit-rv32im-sys/cuda",
  "risc0-zkp/cuda",
  "std",
]
default = ["prove"]
metal = [
  "dep:metal",
  "prove",
  "risc0-circuit-rv32im-sys/metal",
  "risc0-zkp/metal",
]
prove = [
  "dep:bytemuck",
  "dep:crossbeam",
  "dep:lazy-regex",
  "dep:rand",
  "dep:rayon",
  "dep:sha2",
  "dep:tracing-forest",
  "dep:tracing-subscriber",
  "risc0-zkp/prove",
  "risc0-circuit-rv32im-sys",
  "std",
]
seq = ["prove"]
std = ["risc0-zkp/std"]
