[package]
name = "risc0-circuit-rv32im"
description = "RISC Zero circuit for rv32im"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[[bench]]
name = "eval_check"
harness = false

[dependencies]
anyhow = { version = "1.0", default-features = false }
risc0-zkp = { workspace = true }
tracing = { version = "0.1", default-features = false, features = ["attributes"] }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
fil-rustacuda = { version = "0.1", optional = true }
log = "0.4"
rand = { version = "0.8", optional = true }
rayon = { version = "1.5", optional = true }
rustacuda_core = { version = "0.1", optional = true }
rustacuda_derive = { version = "0.1", optional = true }
metal = { version = "0.24", optional = true }

[target.'cfg(target_os = "zkvm")'.dependencies]
risc0-zkvm-platform = { workspace = true }

[dev-dependencies]
criterion = "0.4"
env_logger = "0.10"
test-log = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
glob = "0.3"
sha2 = "0.10"

[features]
cuda = ["dep:fil-rustacuda", "dep:rustacuda_core", "dep:rustacuda_derive", "risc0-zkp/cuda", "std"]
metal = ["dep:metal"]
default = ["prove", "test"]
prove = ["dep:rand", "dep:rayon", "risc0-zkp/prove", "std"]
std = ["risc0-zkp/std"]
test = []
