[package]
name = "risc0-circuit-rv32im"
description = "RISC Zero circuit for rv32im"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[[bench]]
name = "eval_check"
harness = false

[dependencies]
anyhow = { version = "1.0", default-features = false }
bytemuck = "1.13"
derive-debug = "0.1.2"
lazy-regex = { version = "3.1", optional = true }
num-derive = { version = "0.4", optional = true }
num-traits = { version = "0.2", default-features = false, optional = true }
risc0-binfmt = { workspace = true }
risc0-core = { workspace = true }
risc0-zkp = { workspace = true }
risc0-zkvm-platform = { workspace = true }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
cust = { version = "0.3", optional = true }
rand = { version = "0.8", optional = true }
rayon = { version = "1.5", optional = true }
metal = { version = "0.25", optional = true }
risc0-circuit-rv32im-sys = { workspace = true, optional = true }

[dev-dependencies]
criterion = "0.5"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
cuda = [
  "dep:cust",
  "prove",
  "risc0-circuit-rv32im-sys/cuda",
  "risc0-zkp/cuda",
  "std",
]
default = ["prove"]
metal = [
  "dep:metal",
  "prove",
  "risc0-circuit-rv32im-sys/metal",
  "risc0-zkp/metal",
]
prove = [
  "dep:lazy-regex",
  "dep:num-derive",
  "dep:num-traits",
  "dep:rand",
  "dep:rayon",
  "risc0-zkp/prove",
  "risc0-circuit-rv32im-sys",
  "std",
]
std = ["risc0-zkp/std"]
