[package]
name = "cargo-risczero"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "RISC Zero CLI tools"
readme = "README.md"
keywords = ["risc0", "risczero", "tool", "cli", "generate"]

[[bin]]
name = "r0vm"
doc = false

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
cargo-generate = "0.18"
cargo_metadata = "0.17"
clap = { version = "4", features = ["derive"] }
const_format = "0.2"
dirs = "5.0"
docker-generate = "0.1"
flate2 = "1"
fs2 = "0.4"
reqwest = { version = "0.11", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls",
  "gzip",
] }
risc0-build = { workspace = true }
risc0-r0vm = { workspace = true, optional = true }
risc0-zkvm = { workspace = true, optional = true }
serde = { version = "1", features = ["derive"] }
tar = "0.4"
tempfile = "3"
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zip = "0.6"

[build-dependencies]
env_logger = "0.10"
risc0-build = { workspace = true }
zip = "0.6"

[features]
cuda = ["risc0-zkvm/cuda"]
default = ["r0vm"]
docker = []
experimental = ["risc0-zkvm/prove"]
metal = ["risc0-zkvm/metal"]
r0vm = ["dep:risc0-r0vm"]
