[package]
name = "risc0-make-id"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }

risc0-zkvm-host = { version = "0.9", path = "../../sdk/rust/host" }
