name: Benchmark Check

on:
  pull_request:
    branches: [main, "release-*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RISC0_BUILD_LOCKED: 1
  RISC0_TOOLCHAIN_VERSION: v2024-02-08.1

jobs:
  bench:
    runs-on:
      labels: [self-hosted, test, bench, "${{ matrix.os }}", "${{ matrix.device }}"]

    strategy:
      fail-fast: false
      matrix:
        # os: [Linux, macOS]
        # feature: [default]
        # device: [cpu]
        include:
          - os: Linux
            feature: cuda
            device: nvidia_rtx_3090_ti

    env:
      FEATURE: ${{ matrix.feature }}

    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"

      - name: Check out the current PR
        uses: actions/checkout@v4

      - if: matrix.feature == 'cuda'
        uses: ./.github/actions/cuda
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
        with:
          key: ${{ matrix.os }}-${{ matrix.feature }}
          disable_s3: true

      - run: cargo run --bin cargo-risczero --no-default-features -- risczero install --version $RISC0_TOOLCHAIN_VERSION

      - name: Install critcmp
        uses: risc0/cargo-install@b9307573043522ab0d3e3be64a51763b765b52a4
        with:
          crate: critcmp
          version: "0.1.8"

      - name: Run Benchmarks for changes
        run: cargo bench --bench fib -- --save-baseline changes

      - name: Check out the main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Run benchmarks for base
        run: cargo bench --bench fib -- --save-baseline base

      - name: Compare benchmarkes
        run: critcmp base changes
