name: 'Benchmark Check'

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  bench:
    runs-on: [self-hosted, bench, "${{ matrix.os }}", "${{ matrix.device }}"]

    strategy:
      fail-fast: false
      matrix:
        os: [Linux, macOS]
        feature: [default]
        device: [cpu]
        include:
          - os: Linux
            feature: cuda
            device: nvidia_rtx_a5000
          - os: macOS
            feature: metal
            device: intel_uhd_630

    env:
      FEATURE: ${{ matrix.feature }}

    steps:
      - uses: actions/checkout@v3
      - uses: risc0/actions-rs-toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v3

      # Commit just for testing with pending PR, replace with `@risc0`
      - uses: risc0/criterion-compare-action@de006b5bf8b7707003f3da38f5256a19c7651867
        id: criterion-cmp
        with:
          benchName: fib
          branchName: main
          features: ${{ matrix.feature }}
          prettyName: "${{ matrix.os }}-${{ matrix.feature }}"
          outputMarkdown: true

      - name: Write compare markdown to file
        run: echo "${{steps.criterion-cmp.output.markdown}}" > output.md

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ hashFiles('matrix') || 'none' }}
          path: output.md
          if-no-files-found: error

  create-comment:
    runs-on:  ubuntu-22.04
    needs: [ bench ]
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          matrix="$(cat */output.md)"
          echo "::set-output name=matrix::$matrix"
        id: download

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ steps.download.matrix }}
            })
