name: Benchmark Check

on:
  pull_request:
    branches: [main, "release-*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: read

env:
  RISC0_BUILD_LOCKED: 1
  RISC0_TOOLCHAIN_VERSION: v2024-02-08.1

jobs:
  bench:
    runs-on:
      labels: [self-hosted, prod, bench, "${{ matrix.os }}", "${{ matrix.device }}"]

    strategy:
      fail-fast: false
      matrix:
        os: [Linux, macOS]
        feature: [default]
        device: [cpu]
        include:
          - os: Linux
            feature: cuda
            device: nvidia_rtx_3090_ti
          - os: macOS
            feature: metal
            device: apple_m2_pro

    env:
      CI_BENCH_PR: true
      FEATURE: ${{ matrix.feature }}
      DISABLE_S3: ${{ matrix.device == 'nvidia_rtx_3090_ti' }}

    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"

      - name: Check out the current PR
        uses: actions/checkout@v4

      - if: matrix.feature == 'cuda'
        uses: ./.github/actions/cuda
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
        with:
          key: ${{ matrix.os }}-${{ matrix.feature }}
          disable_s3: ${{ env.DISABLE_S3 }}

      - run: cargo run --bin cargo-risczero --no-default-features -- risczero install --version $RISC0_TOOLCHAIN_VERSION

      - name: Run Benchmarks
        run: cargo bench --bench divan -F $FEATURE
