name: Benchmark Check

on:
  pull_request:
    branches: [ main ]
    # Only run benchmarks on changes to following paths:
    paths:
      - 'risc0/**'
      - '.github/workflows/bench_*'

  workflow_dispatch:

jobs:
  bench:
    runs-on: [self-hosted, bench, "${{ matrix.os }}", "${{ matrix.device }}"]

    strategy:
      fail-fast: false
      matrix:
        os: [Linux, macOS]
        feature: [default]
        device: [cpu]
        include:
          - os: Linux
            feature: cuda
            device: nvidia_rtx_a5000
          - os: macOS
            feature: metal
            device: apple_m2_pro

    env:
      FEATURE: ${{ matrix.feature }}
      RUSTC_WRAPPER: sccache

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
      - uses: risc0/criterion-compare-action@risc0
        id: criterion-cmp
        with:
          benchName: fib
          branchName: main
          features: ${{ matrix.feature }}
          prettyName: "${{ matrix.os }}-${{ matrix.feature }}"
          outputMarkdown: true

      - name: Write compare markdown to file
        run: |
          echo "${{ steps.criterion-cmp.outputs.markdown }}" > ${{ matrix.os }}-${{ matrix.feature }}-output.md

      - uses: actions/upload-artifact@v3
        with:
          name: 'md-output'
          path: ${{ matrix.os }}-${{ matrix.feature }}-output.md
          if-no-files-found: error

      # Note: we just push the comment data into artifacts, here
      # the bench_pr_comment.yml picks up after this workflow to make the comment
      # needed because: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
