name: bonsai

on:
  push:
    branches: [ main, 'release-*' ]
  pull_request:
    branches: [ main, 'release-*' ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RISC0_BUILD_LOCKED: 1

jobs:
  bonsai:
    runs-on: [self-hosted, prod, Linux, cpu]
    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - name: checkout dummy commit (submodule bug workaround)
        run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"

      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/cargo-cache
      - uses: ./.github/actions/rustup
      - run: cargo run --bin cargo-risczero -- risczero install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: risc0/foundry-toolchain@2fe7e70b520f62368a0e3c464f997df07ede420f

      # Lint
      - run: forge fmt --check
        working-directory: bonsai/ethereum
      - run: forge fmt --check
        working-directory: bonsai/examples/governance

      # Test
      - run: cargo test --locked --tests -- --include-ignored --nocapture
        working-directory: bonsai
      - run: cargo test --locked
        working-directory: bonsai/examples/governance
      - run: forge test -vvv
        working-directory: bonsai/ethereum
      - run: forge test -vvv
        env:
          TEST_USE_ZKVM: false
        working-directory: bonsai/examples/governance
      - run: forge test -vvv
        env:
          TEST_USE_ZKVM: true
        working-directory: bonsai/examples/governance
