name: foundry

on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Install foundry and use it to lint and test parts of the codebase that use Solidity.
  foundry:
    runs-on: ubuntu-latest
    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - name: checkout dummy commit (submodule bug workaround)
        run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"

      - name: checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install rust
        uses: ./.github/actions/rustup

      - run: cargo run --bin cargo-risczero -- risczero install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Foundry
        uses: risc0/foundry-toolchain@2fe7e70b520f62368a0e3c464f997df07ede420f

      - name: check solidity code formatting in bonsai/ethereum
        run: forge fmt --check
        working-directory: bonsai/ethereum

      - name: check solidity code formatting in bonsai/examples/governance
        run: forge fmt --check
        working-directory: bonsai/examples/governance

      - name: run forge tests in bonsai/ethereum
        run: forge test -vvv
        working-directory: bonsai/ethereum

      - name: run forge tests in bonsai/examples/governance without zkVM
        env:
          TEST_USE_ZKVM: false
        run: forge test -vvv
        working-directory: bonsai/examples/governance

        # TODO(#783): Test currently takes ~1 hour to run, and so it is currently disabled.
        #- name: run forge tests in bonsai/examples/governance with zkVM
        #env:
        #  TEST_USE_ZKVM: true
        #run: forge test -vvv
        #working-directory: bonsai/examples/governance
