name: Update gh-pages

on:
  push:
    branches: [ main ]
    # Only on changes to following paths:
    paths:
      - 'ghpages/**'
      - '.github/workflows/ghpages.yml'

  pull_request:
    branches: [ main ]
    # Only on changes to following paths:
    paths:
      - 'ghpages/**'
      - '.github/workflows/ghpages.yml'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  upload_artifacts:
    runs-on: ubuntu-latest

    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"
      - uses: actions/checkout@v4
        with:
          path: risc0
      - name: Checkout gh-pages repository
        uses: actions/checkout@v4
        with:
          repository: risc0/ghpages
          path: ghpages
          ref: dev
          token: ${{ secrets.BENCHMARK_TOKEN }}
      - name: Push gh-pages
        run: |
          cp -r risc0/ghpages/* ghpages/
          cd ghpages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add --all
          if git diff --cached --exit-code; then
            echo "No changes to commit"
          else
            git commit -m "Add build artifacts"
            git remote set-url origin https://${{ secrets.BENCHMARK_TOKEN }}@github.com/risc0/ghpages.git
            git push -f origin dev
          fi
