name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch the merge commit and origin/HEAD.
          fetch-depth: 2
      - uses: risc0/actions-rs-toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-sort
        uses: risc0/cargo-install@v1
        with:
          crate: cargo-sort
          version: "1.0"
      - run: cargo fmt --all -- --check
      - run: cargo sort --workspace --check
      - run: npx @kt3k/license-checker

  test:
    runs-on: [self-hosted, "${{ matrix.os }}", "${{ matrix.device }}"]
    strategy:
      fail-fast: false
      matrix:
        os: [Linux, macOS]
        feature: [default]
        device: [cpu]
        include:
          - os: Linux
            feature: cuda
            device: nvidia_rtx_a5000
            sccache-arch: x86_64-unknown-linux-musl
          - os: macOS
            feature: metal
            device: intel_uhd_630
            sccache-arch: x86_64-apple-darwin
          - os: Linux
            sccache-arch: x86_64-unknown-linux-musl
          - os: macOS
            sccache-arch: x86_64-apple-darwin
    env:
      FEATURE: ${{ matrix.feature }}
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_ARCH: ${{ matrix.sccache-arch }}
    steps:
      - uses: actions/checkout@v3
      - uses: risc0/actions-rs-toolchain@v1
        with:
          toolchain: stable
      - name: Install sccache
        env:
          URL: https://github.com/mozilla/sccache/releases/download
          SCCACHE_VERSION: v0.3.3
        run: |
          SCCACHE_FILE=sccache-$SCCACHE_VERSION-$SCCACHE_ARCH
          mkdir -p $HOME/.local/bin
          curl -L "$URL/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: cargo test -F $FEATURE
      - run: cargo test -F $FEATURE --tests -- --ignored
      - run: cargo build --manifest-path risc0/wasm/Cargo.toml --target wasm32-unknown-unknown
        if: matrix.device == 'cpu'
      - run: cargo check -F $FEATURE --benches
      - run: cargo check -p bootstrap
        if: matrix.device == 'cpu'
      - run: cargo check -p risc0-build
        if: matrix.device == 'cpu'
      - run: cargo check -F $FEATURE -p risc0-circuit-rv32im
      - run: cargo check -p risc0-core
        if: matrix.device == 'cpu'
      - run: cargo check -F $FEATURE -p risc0-r0vm
      - run: cargo check -F $FEATURE -p risc0-sys
      - run: cargo check -F $FEATURE -p risc0-zkp
      - run: cargo check -F $FEATURE -p risc0-zkvm
      - run: sccache --show-stats

  doc:
    runs-on: [self-hosted, Linux, cpu]
    steps:
      - uses: actions/checkout@v3
      - uses: risc0/actions-rs-toolchain@v1
        with:
          toolchain: stable
      - run: cargo doc
