name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: risc0/actions-rs-toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-sort
        uses: risc0/cargo-install@v1
        with:
          crate: cargo-sort
          version: "1.0"
      - run: cargo fmt --all -- --check
      - run: cargo sort --workspace --check
      - run: npx @kt3k/license-checker

  test:
    runs-on: [self-hosted, "${{ matrix.os }}", "${{ matrix.arch }}"]
    strategy:
      fail-fast: false
      matrix:
        os: [Linux, macOS]
        arch: [X64]
    steps:
      - uses: actions/checkout@v3
      - uses: risc0/actions-rs-toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
        env:
          RUST_BACKTRACE: "1"
      - run: cargo test --tests -- --ignored
        env:
          RUST_BACKTRACE: "1"
      - run: cargo build -p risc0-zkvm -F verify-only --target=wasm32-unknown-unknown
      - run: cargo check --benches

  doc:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v3
      - uses: risc0/actions-rs-toolchain@v1
        with:
          toolchain: stable
      - run: cargo doc
