name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch the merge commit and origin/HEAD.
          fetch-depth: 2
      - uses: risc0/actions-rs-toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-sort
        uses: risc0/cargo-install@v1
        with:
          crate: cargo-sort
          version: "1.0"
      - run: cargo fmt --all -- --check
      - run: cargo sort --workspace --check
      - run: |
          # Check that no source files updated this year have a missing or out-of-date copyright.
          # Locally, use the following command to check that copyrights have been updated.
          # comm -12 <(git diff --name-only --pretty=format: origin/HEAD | sort | uniq) <(npx @kt3k/license-checker | grep 'missing copyright' | sort | cut -d ' ' -f 1)
          set -e
          MISSING_COPYRIGHT="$(comm -12 <(git diff --name-only --pretty=format: HEAD^ | sort | uniq) <(npx @kt3k/license-checker | grep 'missing copyright' | sort | cut -d ' ' -f 1))"
          echo $MISSING_COPYRIGHT
          [ -z "$MISSING_COPYRIGHT" ]

  test:
    runs-on: [self-hosted, "${{ matrix.os }}", "${{ matrix.arch }}"]
    strategy:
      fail-fast: false
      matrix:
        os: [Linux, macOS]
        arch: [X64]
    steps:
      - uses: actions/checkout@v3
      - uses: risc0/actions-rs-toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
        env:
          RUST_BACKTRACE: "1"
      - run: cargo test --tests -- --ignored
        env:
          RUST_BACKTRACE: "1"
      - run: cargo build --manifest-path risc0/wasm/Cargo.toml --target wasm32-unknown-unknown
      - run: cargo check --benches

  doc:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v3
      - uses: risc0/actions-rs-toolchain@v1
        with:
          toolchain: stable
      - run: cargo doc
