name: Website preview
on:
  pull_request:
    branches: [main]
    paths:
      - "website/**"
  workflow_dispatch:

concurrency:
  group: preview-${{ github.event_name }}-${{ github.event.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  dev:
    runs-on: ubuntu-20.04
    env:
      PREVIEW_REPO: risc0/website-preview
      PAGES_BASE: https://risc0.github.io/website-preview/

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn install
        working-directory: website

      # This will calculate the base URL for the website, based on the event that triggered the workflow.
      # Leave this step as it is, unless you know what you're doing.
      - name: Determine base URL
        id: baseurl
        run: |
          if [ "${{ github.event_name }}" == "pull_request_target" ]; then
            full="${{ env.PAGES_BASE }}/${{ github.repository }}/pr/${{ github.event.number }}"
          else
            full="${{ env.PAGES_BASE }}/${{ github.repository }}/branch/${{ github.ref_name }}"
          fi

          relative=/$(echo $full | cut -d/ -f4-)

          echo "full=$full" >> $GITHUB_OUTPUT
          echo "relative=$relative" >> $GITHUB_OUTPUT
        shell: bash

      # Run your usual build command, but make sure to use the correct base URL
      # This example assumes you're using React, and that you're using the PUBLIC_URL env variable
      - name: Build
        run: yarn build
        working-directory: website
        env:
          PUBLIC_URL: ${{ steps.baseurl.outputs.relative }}

      - uses: EndBug/pages-preview@v1
        with:
          build_dir: website/build
          preview_base_url: ${{ env.PAGES_BASE }}
          preview_repo: ${{ env.PREVIEW_REPO }}
          preview_token: ${{ secrets.PREVIEW_TOKEN }}
