name: website-test

on:
  merge_group:
  pull_request:
    branches: [main, "release-*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_TOOLCHAIN_VERSION: test-release-2

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      versions: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: risc0/paths-filter@4067d885736b84de7c414f582ac45897079b0a78
        id: filter
        with:
          filters: |
            main:
              - bonsai/**
              - risc0/**
              - website/api/**
              - website/doc-test/main/**
              - website/docs/**
            version-0.18:
              - website/api_versioned_docs/version-0.18/**
              - website/doc-test/version-0.18/**
            version-0.19:
              - website/api_versioned_docs/version-0.19/**
              - website/doc-test/version-0.19/**

  doc-test:
    needs: changes
    strategy:
      matrix:
        version: ${{ fromJSON(needs.changes.outputs.versions) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Recursive checkout required to build Solidity contracts and bindings.
          submodules: recursive
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
        with:
          key: Linux-default
      - uses: risc0/foundry-toolchain@2fe7e70b520f62368a0e3c464f997df07ede420f
        with:
          version: nightly-34f684ddfacc5b2ed371353ba6f730c485616ffe
      - run: cargo run --bin cargo-risczero --no-default-features -- risczero install --version $RISC0_TOOLCHAIN_VERSION

      - name: build ${{ matrix.version }}
        run: cargo test --release --no-run
        working-directory: website/doc-test/${{ matrix.version }}
      - name: test ${{ matrix.version }}
        run: cargo test --release
        working-directory: website/doc-test/${{ matrix.version }}

      - run: sccache --show-stats
