[package]
name = "substrate-minimal-runtime"
version = "0.1.0"
description = "Minimal Substrate runtime for testing compatibility"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-support = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk/", branch = "release-polkadot-v1.1.0" }
risc0-zkvm = { workspace = true, default-features = false }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk/", branch = "release-polkadot-v1.1.0", features = ["serde"] }

[build-dependencies]
substrate-wasm-builder = { version = "5.0.0-dev", git = "https://github.com/paritytech/polkadot-sdk/", optional = true, branch = "release-polkadot-v1.1.0" }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"substrate-wasm-builder",
]
